import os
import json
import importlib.util

# Load the existing knowledge base
spec = importlib.util.spec_from_file_location("tpf_knowledge", "backend/llm/tpf_knowledge.py")
tpf_knowledge = importlib.util.module_from_spec(spec)
spec.loader.exec_module(tpf_knowledge)

KNOWLEDGE = tpf_knowledge.KNOWLEDGE

# Expand the Z commands, especially Display (ZD) and System entries
more_z_commands = {
    "ZDSYS": "Display system. Displays z/TPF system status, MDB state, and cross-processor communication metrics.",
    "ZDECB": "Display ECB data. (Diagnostic) Dumps ECB data levels, specific core block contents, and registers.",
    "ZDHIS": "Display history. Shows historical system events or tape mounts.",
    "ZDTIM": "Display time. Displays current system clock and TOD settings.",
    "ZDMSG": "Display message. Shows routing parameters for specific message numbers.",
    "ZDSCT": "Display sector. Displays hardware sector formats or usage.",
    "ZDCPD": "Display CP definitions. Shows Central Processor configuration.",
    "ZDDTA": "Display data capture. Shows active data capture scenarios.",
    "ZDPVL": "Display pool volumes. Shows disk pool volume attributes.",
    "ZDUIN": "Display UINs. Displays Unique Identifier Numbers usage.",
    "ZDTCP": "Display TCP/IP. Shows socket status and TCP/IP stack stats.",
    "ZDTRP": "Display traps. Shows active diagnostic traps in the system.",
    "ZSYSM": "System messages. Toggle and configure system message processing.",
    "ZPING": "Ping TCP/IP node. Verify network connectivity from z/TPF.",
    "ZSTAT": "System statistics. Displays real-time z/TPF system performance metrics, ECB utilization, and core block levels.",
    "ZTRAC": "System trace. Start/Stop specific traces for programs or subsystems.",
    "ZTIMA": "Time alteration. Manage system timeout thresholds."
}

# Add them to the dictionary
KNOWLEDGE["z_commands"].update(more_z_commands)

# Add an entirely new section for Advisor Troubleshooting
KNOWLEDGE["advisor_troubleshooting"] = {
    "ECB_RESOURCE_LOCKOUT": "If an ECB is hanging or locking resources (FIWHC without UNFRC), the Advisor should recommend checking active ECBs with ZECB or ZDECB and verifying the macro sequence.",
    "MEMORY_LEAK": "If GETCC is heavily used without RELCC, the Advisor should recommend checking system core blocks using ZPOOL and ZSTAT to monitor depletion.",
    "NETWORK_HANG": "For socket timeouts or TCP/IP issues, the Advisor should recommend using ZINET and ZDTCP to display network connections and check DAEMON status.",
    "SYSTEM_CRASH_OR_CTL": "If an entry might cause a CTL- dump (e.g. invalid memory access), the Advisor should recommend setting a trap with ZTRAP and analyzing the dump with ZDUMP.",
    "PERFORMANCE_DEGRADATION": "For slow entries, recommend using ZMEAS and ZSTAT to track CPU and IO utilization."
}

# Update the advisor prompt guidance
KNOWLEDGE["advisor_guidance"] = [
    "When providing recommendations, if an issue matches a known troubleshooting category (e.g. MEMORY_LEAK), always explicitly suggest the appropriate Z commands (e.g. ZPOOL, ZSTAT) for the operator to run.",
    "Act as an end-to-end Chat Advisor: if the Coder generates a piece of REXX or TPF entry that seems risky, recommend the exact diagnostic Z command needed to monitor it in production."
]

knowledge_file_content = f"""# Auto-generated by expand_advisor_knowledge.py
KNOWLEDGE = {json.dumps(KNOWLEDGE, indent=4)}
"""

with open("backend/llm/tpf_knowledge.py", "w", encoding="utf-8") as f:
    f.write(knowledge_file_content)

print(f"Successfully expanded KNOWLEDGE base. Total Z commands: {len(KNOWLEDGE['z_commands'])}")
