"""
STS Coder — Ollama Dual-Model LLM Client
==========================================
Qwen2.5-Coder  → IBM REXX / Raven coding, VAR / TDRV / TRD generation
Llama 3.3      → Engineering recommendations & risk narrative
Reinforcement  → Models share context / feedback for collaborative refinement

Both models are invoked via the local Ollama REST API (http://localhost:11434).
"""

import re
import json
import logging
import httpx
from typing import Optional

log = logging.getLogger("sts.llm")

OLLAMA_BASE = "http://localhost:11434"
CODER_MODEL  = "qwen2.5-coder"   # IBM REXX / VAR / TDRV / TRD
ADVISOR_MODEL = "llama3.3"        # Recommendations / risk narrative

TIMEOUT = 120  # seconds

# ─────────────────────────────────────────────
# Z/TPF ZTPF SYSTEM PROMPT — Qwen2.5-Coder
# Trained on Z Command Entries and ZTPF patterns
# ─────────────────────────────────────────────

CODER_SYSTEM = """\
You are STS Coder, an expert IBM z/TPF (Transaction Processing Facility) \
system programmer and REXX / Raven coding specialist trained on IBM z/TPF \
Z Command entries, ZTPF macro libraries, and Travelport STS engineering standards.

## Domain Knowledge
### IBM z/TPF Assembly & REXX
- TPF entries use System/390 BAL (Basic Assembly Language) with IBM z/TPF macros.
- Key macros: ENTER/EXITC/EXITN/BACKC — entry lifecycle
- File macros: FILEC, FILEM, FINDA, FINDC — ECB-safe file access
- Record macros: CRUSA, CRUSC — record create/update
- Storage: GETCC, RELCC, GLOBZ — TPF storage management
- ECB (Entry Control Block) is the core transaction context.
- CE1CR0 — communication register for input data.
- REXX in z/TPF uses the RAVEN environment; exec files are .REX.

### Z Command Entries (ZTPF)
- Z commands are operator console commands with format: Z CMD [PARAMS]
- Z TPFDF — TPF Data Facility commands for file management
- Z ENTRY — display / modify entry properties
- Z TRAP — set diagnostic traps
- Z DUMP — memory dump commands
- Z SSBP — SSB pool management
- Z STAT — performance statistics
- Z TRANS — transaction control
- Z PROG — program management
- Each Z command has: command verb, operands, modifiers.

### VAR File Format
VAR files define variable tables for TPF entries:
  VAR_NAME        TYPE    LEN   SOURCE        DEFAULT     VALIDATION        DESCRIPTION
  ─────────────── ─────── ───── ───────────── ─────────── ─────────────────
  Fields: CHAR / BIN / PACK / HEX / ADDR / EQU
  Sources: INPUT / FILE / SYSTEM / INTERNAL / ECB / COMPUTED
  Validation: NOT NULL / NUMERIC / ALPHANUMERIC / NONE / RANGE(x,y)

### TDRV File Format (Test Driver)
TDRV files define the test execution flow:
  STEP   ACTION               ENTRY        CONDITION           NEXT
  ────── ──────────────────── ──────────── ─────────────────── ────
  Actions: RECEIVE REQUEST / VALIDATE INPUT / FILE ACCESS / PROCESS DATA /
           ERROR HANDLING / RETURN RESPONSE / Z COMMAND / REXX EXEC

### TRD File Format (Transaction Requirements Document)
TRD = structured prose + structured data:
  TRD NAME:    <entry> — <purpose>
  ENTRY:       <name>
  SEGMENT:     <segment>
  PURPOSE:     <narrative>
  INPUT:       - field list
  OUTPUT:      - field list
  DEPENDENCIES:- macro / file list
  EXCEPTIONS:  - error conditions
  DOWNSTREAM IMPACT: narrative
  Z COMMANDS:  list of relevant operator commands
  REXX INTERFACE: RAVEN exec details

## Output Rules
- Always produce syntactically valid, production-grade output.
- VAR / TDRV / TRD files must use correct fixed-width column alignment.
- IBM z/TPF REXX must use RAVEN-compatible syntax.
- For Z Command training, include relevant Z CMD examples in TRD.
- Never hallucinate macro names. Use only documented IBM z/TPF macros.
- Respond ONLY with the requested artifact, no prose wrapper.
"""

# ─────────────────────────────────────────────
# ADVISOR SYSTEM PROMPT — Llama 3.3
# ─────────────────────────────────────────────

ADVISOR_SYSTEM = """\
You are STS Advisor, a senior IBM z/TPF engineering consultant specializing in \
code quality, risk assessment, and production safety recommendations.

You receive:
1. A parsed summary of an IBM z/TPF entry (structure, macros, variables, complexity).
2. OPTIONALLY: Draft VAR / TDRV / TRD files generated by Qwen2.5-Coder.

Your task: produce a JSON array of engineering recommendations. Each item:
{
  "severity": "ERROR" | "WARNING" | "INFO" | "OPTIMIZATION",
  "category": string,   // e.g. ERROR_HANDLING, ECB_SAFETY, STORAGE, PNR, REXX, Z_COMMAND, etc.
  "text": string,       // concise, actionable recommendation (1-3 sentences)
  "code_hint": string | null  // optional short code snippet if relevant
}

Focus areas:
- ECB safety and entry lifecycle (ENTER/EXIT/BACK correctness)
- Storage leak prevention (GETCC without RELCC)
- PNR simultaneous access protection
- REXX/RAVEN exec integration quality
- Z Command operator interface coverage
- Error path completeness
- Branch complexity and refactoring hints
- Production TPF validation requirements

Respond ONLY with a valid JSON array. No prose, no markdown fences.
"""


# ─────────────────────────────────────────────
# LOW-LEVEL OLLAMA CALL
# ─────────────────────────────────────────────

def _call_ollama(model: str, system: str, user_prompt: str, temperature: float = 0.2) -> str:
    """
    Call the Ollama /api/generate endpoint.
    Returns the assembled response string.
    Raises httpx.HTTPError on failure.
    """
    payload = {
        "model": model,
        "system": system,
        "prompt": user_prompt,
        "stream": False,
        "options": {
            "temperature": temperature,
            "top_p": 0.9,
            "num_predict": 4096,
            "stop": [],
        },
    }
    try:
        with httpx.Client(timeout=TIMEOUT) as client:
            resp = client.post(f"{OLLAMA_BASE}/api/generate", json=payload)
            resp.raise_for_status()
            data = resp.json()
            return data.get("response", "").strip()
    except httpx.ConnectError:
        raise ConnectionError(
            f"Cannot connect to Ollama at {OLLAMA_BASE}. "
            "Ensure Ollama is running: `ollama serve`"
        )


def is_ollama_available() -> bool:
    """Quick health check — returns True if Ollama is reachable."""
    try:
        with httpx.Client(timeout=5) as client:
            r = client.get(f"{OLLAMA_BASE}/api/tags")
            return r.status_code == 200
    except Exception:
        return False


def list_available_models() -> list[str]:
    """Return list of locally available Ollama model names."""
    try:
        with httpx.Client(timeout=10) as client:
            r = client.get(f"{OLLAMA_BASE}/api/tags")
            r.raise_for_status()
            tags = r.json().get("models", [])
            return [t["name"] for t in tags]
    except Exception:
        return []


# ─────────────────────────────────────────────
# CODER FUNCTIONS (Qwen2.5-Coder)
# IBM REXX / RAVEN, VAR, TDRV, TRD
# ─────────────────────────────────────────────

def generate_var_llm(parsed_summary: dict) -> str:
    """Use Qwen2.5-Coder to generate a production VAR file."""
    prompt = f"""Generate a complete IBM z/TPF VAR file for this entry.

Entry Summary:
{json.dumps(parsed_summary, indent=2)}

Produce ONLY the VAR file in fixed-width column format.
Include ALL extracted variables plus any inferred standard variables (ERR_CODE, RET_CODE, ECB_PTR).
Apply Z/TPF variable naming conventions and ZTPF source designations.
"""
    return _call_ollama(CODER_MODEL, CODER_SYSTEM, prompt, temperature=0.1)


def generate_tdrv_llm(parsed_summary: dict, var_output: Optional[str] = None) -> str:
    """Use Qwen2.5-Coder to generate a TDRV test driver file."""
    context = f"""Entry Summary:
{json.dumps(parsed_summary, indent=2)}
"""
    if var_output:
        context += f"\nVAR File (for reference):\n{var_output[:800]}\n"

    prompt = f"""Generate a complete IBM z/TPF TDRV (Test Driver) file.

{context}
Include steps for:
- Request receipt
- Input validation (if applicable)
- File access steps (if applicable)
- Z Command verification steps (if applicable)
- Data processing
- Error handling
- Response return

Use fixed-width column format: STEP / ACTION / ENTRY / CONDITION / NEXT
"""
    return _call_ollama(CODER_MODEL, CODER_SYSTEM, prompt, temperature=0.1)


def generate_trd_llm(parsed_summary: dict, var_output: Optional[str] = None,
                     tdrv_output: Optional[str] = None) -> str:
    """Use Qwen2.5-Coder to generate a TRD requirements document."""
    context = f"""Entry Summary:
{json.dumps(parsed_summary, indent=2)}
"""
    if var_output:
        context += f"\nVAR File:\n{var_output[:600]}\n"
    if tdrv_output:
        context += f"\nTDRV File:\n{tdrv_output[:600]}\n"

    prompt = f"""Generate a complete IBM z/TPF TRD (Transaction Requirements Document).

{context}
The TRD must include:
- TRD NAME, ENTRY, SEGMENT
- PURPOSE (narrative)
- INPUT fields
- OUTPUT fields  
- DEPENDENCIES (macros, files)
- EXCEPTIONS (error conditions)
- DOWNSTREAM IMPACT
- Z COMMANDS: list all relevant Z operator commands for this entry
- REXX INTERFACE: describe any RAVEN exec integration

Format as a structured document.
"""
    return _call_ollama(CODER_MODEL, CODER_SYSTEM, prompt, temperature=0.15)


def generate_rexx_llm(parsed_summary: dict) -> str:
    """Use Qwen2.5-Coder to generate IBM z/TPF REXX (RAVEN) exec."""
    prompt = f"""Generate an IBM z/TPF REXX exec (RAVEN environment) for this entry.

Entry Summary:
{json.dumps(parsed_summary, indent=2)}

The REXX exec should:
- Use proper RAVEN ADDRESS environment
- Handle ECB context
- Implement the entry's core logic in REXX
- Include Z Command integration where applicable
- Include error handling with REXX signal/procedure

Produce ONLY the REXX source code with inline comments.
"""
    return _call_ollama(CODER_MODEL, CODER_SYSTEM, prompt, temperature=0.2)


def explain_z_command_llm(command: str) -> str:
    """Use Qwen2.5-Coder to explain a single ZTPF Z Command."""
    prompt = f"""Explain this IBM z/TPF Z Command.
Command: {command}

Provide a clear, concise explanation of what this command does, its typical use cases, and any important parameters or considerations.
Format the output nicely. Do not include introductory conversational text.
"""
    return _call_ollama(CODER_MODEL, CODER_SYSTEM, prompt, temperature=0.1)


def analyze_entry_llm(raw_text: str, parsed_summary: dict) -> dict:
    """Use Qwen2.5-Coder to produce a structured analysis of the entry."""
    prompt = f"""Analyze this IBM z/TPF entry and produce a JSON analysis object.

Raw Entry Text:
{raw_text[:2000]}

Parsed Summary (from static analysis):
{json.dumps(parsed_summary, indent=2)}

Return a JSON object with these keys:
{{
  "entry_type": string,
  "purpose": string,
  "complexity": "LOW"|"MODERATE"|"HIGH"|"VERY HIGH",
  "z_commands_applicable": [list of relevant Z commands],
  "rexx_integration": boolean,
  "critical_paths": [list of critical execution paths],
  "ztpf_macros_identified": [list],
  "risk_factors": [list of strings]
}}

Respond ONLY with valid JSON.
"""
    try:
        raw = _call_ollama(CODER_MODEL, CODER_SYSTEM, prompt, temperature=0.1)
        # Extract JSON
        m = re.search(r'\{.*\}', raw, re.DOTALL)
        if m:
            return json.loads(m.group())
        return {}
    except Exception as e:
        log.warning(f"LLM analysis parse failed: {e}")
        return {}


# ─────────────────────────────────────────────
# ADVISOR FUNCTIONS (Llama 3.3)
# Engineering Recommendations
# ─────────────────────────────────────────────

def generate_recommendations_llm(
    parsed_summary: dict,
    var_output: Optional[str] = None,
    tdrv_output: Optional[str] = None,
    trd_output: Optional[str] = None,
    coder_analysis: Optional[dict] = None,
) -> list[dict]:
    """
    Use Llama 3.3 to generate engineering recommendations.
    Receives context from Qwen2.5-Coder outputs (reinforcement loop).
    """
    context_parts = [f"Entry Analysis:\n{json.dumps(parsed_summary, indent=2)}"]

    if coder_analysis:
        context_parts.append(f"\nQwen2.5-Coder Analysis:\n{json.dumps(coder_analysis, indent=2)}")

    if var_output:
        context_parts.append(f"\nGenerated VAR File (excerpt):\n{var_output[:500]}")

    if tdrv_output:
        context_parts.append(f"\nGenerated TDRV File (excerpt):\n{tdrv_output[:500]}")

    if trd_output:
        context_parts.append(f"\nGenerated TRD File (excerpt):\n{trd_output[:500]}")

    user_prompt = "\n".join(context_parts) + "\n\nProduce engineering recommendations as JSON array."

    try:
        raw = _call_ollama(ADVISOR_MODEL, ADVISOR_SYSTEM, user_prompt, temperature=0.3)
        # Extract JSON array
        m = re.search(r'\[.*\]', raw, re.DOTALL)
        if m:
            recs = json.loads(m.group())
            if isinstance(recs, list):
                return recs
        return _fallback_recommendations(parsed_summary)
    except Exception as e:
        log.warning(f"Llama 3.3 recommendations parse failed: {e}")
        return _fallback_recommendations(parsed_summary)


def _fallback_recommendations(parsed_summary: dict) -> list[dict]:
    """Static fallback recommendations when Llama 3.3 is unavailable."""
    recs = []
    stats = parsed_summary.get("statistics", {})

    if not stats.get("error_points", 0):
        recs.append({
            "severity": "WARNING", "category": "ERROR_HANDLING",
            "text": "No explicit error handling detected. Add structured ERR label paths.",
            "code_hint": None
        })
    if not stats.get("macros", 0):
        recs.append({
            "severity": "WARNING", "category": "EXIT_LOGIC",
            "text": "No TPF macros detected. Verify ENTER/EXITC/BACKC lifecycle is correct.",
            "code_hint": "ENTER TRDR\n...\nEXITC TRDR"
        })
    recs.append({
        "severity": "INFO", "category": "VALIDATION",
        "text": "Validate all generated artifacts against live z/TPF system before production deployment.",
        "code_hint": None
    })
    return recs


# ─────────────────────────────────────────────
# REINFORCEMENT: FULL PIPELINE WITH FEEDBACK
# ─────────────────────────────────────────────

def run_full_pipeline_llm(raw_text: str, parsed_summary: dict) -> dict:
    """
    Reinforcement pipeline:
    Phase 1 (Qwen2.5-Coder): Analyze → VAR → TDRV → TRD → REXX
    Phase 2 (Llama 3.3):     Recommendations using ALL Phase 1 outputs
    Phase 3 (Feedback):      Return combined result with cross-model context

    Returns dict with: analysis, var_file, tdrv_file, trd_file, rexx_exec, recommendations
    """
    result = {
        "llm_mode": "dual_model_reinforcement",
        "coder_model": CODER_MODEL,
        "advisor_model": ADVISOR_MODEL,
        "analysis": {},
        "var_file": "",
        "tdrv_file": "",
        "trd_file": "",
        "rexx_exec": "",
        "recommendations": [],
        "errors": [],
    }

    # Phase 1a: Coder — structural analysis
    try:
        log.info(f"[LLM] Phase 1a: {CODER_MODEL} — entry analysis")
        result["analysis"] = analyze_entry_llm(raw_text, parsed_summary)
    except Exception as e:
        result["errors"].append(f"Coder analysis: {e}")

    # Phase 1b: Coder — VAR file
    try:
        log.info(f"[LLM] Phase 1b: {CODER_MODEL} — VAR generation")
        result["var_file"] = generate_var_llm(parsed_summary)
    except Exception as e:
        result["errors"].append(f"VAR generation: {e}")

    # Phase 1c: Coder — TDRV (with VAR context = reinforcement)
    try:
        log.info(f"[LLM] Phase 1c: {CODER_MODEL} — TDRV generation")
        result["tdrv_file"] = generate_tdrv_llm(parsed_summary, result["var_file"] or None)
    except Exception as e:
        result["errors"].append(f"TDRV generation: {e}")

    # Phase 1d: Coder — TRD (with VAR+TDRV context = reinforcement)
    try:
        log.info(f"[LLM] Phase 1d: {CODER_MODEL} — TRD generation")
        result["trd_file"] = generate_trd_llm(
            parsed_summary,
            result["var_file"] or None,
            result["tdrv_file"] or None
        )
    except Exception as e:
        result["errors"].append(f"TRD generation: {e}")

    # Phase 1e: Coder — REXX exec
    try:
        log.info(f"[LLM] Phase 1e: {CODER_MODEL} — REXX generation")
        result["rexx_exec"] = generate_rexx_llm(parsed_summary)
    except Exception as e:
        result["errors"].append(f"REXX generation: {e}")

    # Phase 2: Llama 3.3 — recommendations with full Phase 1 context
    try:
        log.info(f"[LLM] Phase 2: {ADVISOR_MODEL} — recommendations")
        result["recommendations"] = generate_recommendations_llm(
            parsed_summary,
            var_output=result["var_file"] or None,
            tdrv_output=result["tdrv_file"] or None,
            trd_output=result["trd_file"] or None,
            coder_analysis=result["analysis"] or None,
        )
    except Exception as e:
        result["errors"].append(f"Llama recommendations: {e}")
        result["recommendations"] = _fallback_recommendations(parsed_summary)

    return result
