"""
STS Coder — TDR File Generator
================================
Generates Technical Requirement Description from ParsedEntry.
Covers business purpose, entry logic, process flow,
variable dependencies, exceptions, and downstream impact.
"""

from datetime import datetime, timezone
from parser.tpf_parser import ParsedEntry


def generate_tdr_file(entry: ParsedEntry) -> str:
    """Generate complete TDR file output string."""
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines: list[str] = []

    lines.append("=" * 80)
    lines.append(f"  TDR FILE — {entry.name}")
    lines.append(f"  Generated by STS Coder | {ts}")
    lines.append("=" * 80)
    lines.append("")

    lines.append(f"TDR NAME:      {entry.name} — {entry.purpose}")
    lines.append(f"ENTRY:         {entry.name}")
    lines.append(f"SEGMENT:       {entry.segment}")
    lines.append(f"LINE COUNT:    {entry.line_count}")
    lines.append("")

    # Purpose
    lines.append("PURPOSE:")
    lines.append(f"  {entry.purpose}")
    lines.append("")

    # Inputs
    lines.append("INPUT:")
    for inp in entry.inputs:
        lines.append(f"  - {inp}")
    lines.append("")

    # Outputs
    lines.append("OUTPUT:")
    for out in entry.outputs:
        lines.append(f"  - {out}")
    lines.append("")

    # Variables summary
    lines.append("VARIABLE SUMMARY:")
    lines.append(f"  Total Variables:  {len(entry.variables)}")
    type_counts: dict[str, int] = {}
    for v in entry.variables:
        type_counts[v.var_type] = type_counts.get(v.var_type, 0) + 1
    for vt, count in type_counts.items():
        lines.append(f"    {vt}: {count}")
    lines.append("")

    # Dependencies
    lines.append("DEPENDENCIES:")
    if entry.dependencies:
        for dep in entry.dependencies:
            lines.append(f"  - {dep}")
    else:
        lines.append("  UNKNOWN - Requires TPF validation")
    lines.append("")

    # Macros
    lines.append("MACROS CALLED:")
    if entry.macros:
        for mc in entry.macros:
            lines.append(f"  - {mc.name}  {mc.operands}")
    else:
        lines.append("  NONE DETECTED")
    lines.append("")

    # File references
    lines.append("FILE REFERENCES:")
    if entry.file_ops:
        for fo in entry.file_ops:
            lines.append(f"  - {fo}")
    else:
        lines.append("  NONE DETECTED")
    lines.append("")

    # ECB usage
    lines.append("ECB REFERENCES:")
    if entry.ecb_refs:
        for ecb in entry.ecb_refs:
            lines.append(f"  - {ecb}")
    else:
        lines.append("  NONE DETECTED")
    lines.append("")

    # Process flow summary
    lines.append("PROCESS FLOW:")
    lines.append(f"  1. Entry point: {entry.name}")
    step = 2
    if any(i.category == "compare" for i in entry.instructions):
        lines.append(f"  {step}. Input validation and field checking")
        step += 1
    if entry.file_ops:
        lines.append(f"  {step}. File access: {', '.join(entry.file_ops[:5])}")
        step += 1
    if any(i.category in ("data", "arithmetic") for i in entry.instructions):
        lines.append(f"  {step}. Data processing and transformation")
        step += 1
    if entry.error_points:
        lines.append(f"  {step}. Error handling and exception routing")
        step += 1
    macro_names = {m.name for m in entry.macros}
    exit_type = "EXITC/EXITN" if macro_names & {"EXITC", "EXITN"} else "BACK" if macro_names & {"BACKC", "BACK"} else "RETURN"
    lines.append(f"  {step}. Exit via {exit_type}")
    lines.append("")

    # Exceptions
    lines.append("EXCEPTIONS:")
    if entry.error_points:
        for ep in entry.error_points[:10]:
            lines.append(f"  - {ep[:70]}")
    else:
        lines.append("  UNKNOWN - Requires TPF validation")
    lines.append("")

    # Branch analysis
    lines.append("BRANCH ANALYSIS:")
    lines.append(f"  Total Branches:   {len(entry.branches)}")
    if entry.branches:
        targets = [b.target for b in entry.branches[:15]]
        lines.append(f"  Branch Targets:   {', '.join(targets)}")
    lines.append("")

    # Downstream impact
    lines.append("DOWNSTREAM IMPACT:")
    lines.append("  Requires validation against production TPF system.")
    if entry.file_ops:
        lines.append(f"  File dependencies: {', '.join(entry.file_ops[:5])}")
    if macro_names & {"SERVC", "SVCRC"}:
        lines.append("  Service calls detected — verify downstream service availability.")
    lines.append("")

    return "\n".join(lines)
