"""
STS Coder — TDRV File Generator
=================================
Generates driver flow documentation from ParsedEntry.
Maps entry invocation sequence, validation branches,
success/fail conditions, and dependency chain.
"""

from datetime import datetime, timezone
from parser.tpf_parser import ParsedEntry


def _pad(text: str, width: int) -> str:
    return str(text).ljust(width)


def generate_tdrv_file(entry: ParsedEntry) -> str:
    """Generate complete TDRV file output string."""
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines: list[str] = []

    lines.append("=" * 80)
    lines.append(f"  TDRV FILE — {entry.name}")
    lines.append(f"  Segment:  {entry.segment}")
    lines.append(f"  Generated by STS Coder | {ts}")
    lines.append("=" * 80)
    lines.append("")

    header = (
        _pad("STEP", 7)
        + _pad("ACTION", 22)
        + _pad("ENTRY", 14)
        + _pad("CONDITION", 22)
        + "NEXT"
    )
    lines.append(header)
    lines.append("─" * 80)

    steps = _build_steps(entry)
    for s in steps:
        row = (
            _pad(s["step"], 7)
            + _pad(s["action"], 22)
            + _pad(s["entry"], 14)
            + _pad(s["condition"], 22)
            + s["next"]
        )
        lines.append(row)

    lines.append("─" * 80)
    lines.append(f"TOTAL STEPS: {len(steps)}")
    lines.append("")

    # Dependency chain
    lines.append("DEPENDENCY CHAIN:")
    if entry.dependencies:
        for dep in entry.dependencies:
            lines.append(f"  → {dep}")
    else:
        lines.append("  UNKNOWN - Requires TPF validation")
    lines.append("")

    return "\n".join(lines)


def _build_steps(entry: ParsedEntry) -> list[dict]:
    """Build TDRV step list based on parsed entry structure."""
    steps = []
    step_num = 1
    name = entry.name

    # Step 1: Receive
    macro_names = {m.name for m in entry.macros}
    has_enter = bool(macro_names & {"ENTER", "ENTRC", "ENPTS"})

    steps.append({
        "step": str(step_num).zfill(2),
        "action": "ENTRY INITIALIZATION" if has_enter else "RECEIVE REQUEST",
        "entry": name,
        "condition": "ENTER MACRO" if has_enter else "INPUT RECEIVED",
        "next": str(step_num + 1).zfill(2),
    })
    step_num += 1

    # Step 2: Validation (if compare instructions exist)
    has_validation = any(i.category == "compare" for i in entry.instructions)
    if has_validation:
        steps.append({
            "step": str(step_num).zfill(2),
            "action": "VALIDATE INPUT",
            "entry": f"{name}_V",
            "condition": "VALID",
            "next": str(step_num + 1).zfill(2),
        })
        step_num += 1

    # Step 3: File access (if file ops)
    if entry.file_ops:
        steps.append({
            "step": str(step_num).zfill(2),
            "action": "FILE ACCESS",
            "entry": f"{name}_F",
            "condition": "RECORD FOUND",
            "next": str(step_num + 1).zfill(2),
        })
        step_num += 1

    # Step 4: PNR (if PNR macros)
    if macro_names & {"PNRCC", "PNRAC"}:
        steps.append({
            "step": str(step_num).zfill(2),
            "action": "PNR PROCESSING",
            "entry": f"{name}_PNR",
            "condition": "PNR ACCESSED",
            "next": str(step_num + 1).zfill(2),
        })
        step_num += 1

    # Step 5: Data processing
    has_data = any(i.category in ("data", "arithmetic") for i in entry.instructions)
    if has_data:
        steps.append({
            "step": str(step_num).zfill(2),
            "action": "PROCESS DATA",
            "entry": f"{name}_P",
            "condition": "SUCCESS",
            "next": str(step_num + 1).zfill(2),
        })
        step_num += 1

    # Step 6: Service call (if present)
    if macro_names & {"SERVC", "SVCRC"}:
        steps.append({
            "step": str(step_num).zfill(2),
            "action": "SERVICE CALL",
            "entry": f"{name}_S",
            "condition": "SERVICE OK",
            "next": str(step_num + 1).zfill(2),
        })
        step_num += 1

    # Step 7: Error handling (if error points)
    if entry.error_points:
        steps.append({
            "step": str(step_num).zfill(2),
            "action": "ERROR HANDLING",
            "entry": f"{name}_E",
            "condition": "ERROR DETECTED",
            "next": str(step_num + 1).zfill(2),
        })
        step_num += 1

    # Step 8: Storage release (if RELCC/RELFC)
    if macro_names & {"RELCC", "RELFC", "RLASC"}:
        steps.append({
            "step": str(step_num).zfill(2),
            "action": "RELEASE STORAGE",
            "entry": f"{name}_REL",
            "condition": "RELEASED",
            "next": str(step_num + 1).zfill(2),
        })
        step_num += 1

    # Final: Return response
    has_exit = bool(macro_names & {"EXITC", "EXITN", "BACKC", "BACK"})
    steps.append({
        "step": str(step_num).zfill(2),
        "action": "EXIT / RETURN" if has_exit else "RETURN RESPONSE",
        "entry": f"{name}_R",
        "condition": "COMPLETE",
        "next": "END",
    })

    return steps
