"""
STS Coder — VAR File Generator
================================
Generates production-grade VAR file definitions from ParsedEntry.
Enterprise fixed-width formatting.
"""

from datetime import datetime, timezone
from parser.tpf_parser import ParsedEntry


def _pad(text: str, width: int) -> str:
    return str(text).ljust(width)


def generate_var_file(entry: ParsedEntry) -> str:
    """Generate complete VAR file output string."""
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines: list[str] = []

    lines.append("=" * 104)
    lines.append(f"  VAR FILE — {entry.name}")
    lines.append(f"  Segment:  {entry.segment}")
    lines.append(f"  Generated by STS Coder | {ts}")
    lines.append("=" * 104)
    lines.append("")

    # Header row
    header = (
        _pad("VAR_NAME", 18)
        + _pad("TYPE", 8)
        + _pad("LEN", 6)
        + _pad("SOURCE", 14)
        + _pad("DEFAULT", 12)
        + _pad("VALIDATION", 18)
        + "DESCRIPTION"
    )
    lines.append(header)
    lines.append("─" * 104)

    vars_to_render = entry.variables if entry.variables else _default_vars()

    for v in vars_to_render:
        row = (
            _pad(v.name, 18)
            + _pad(v.var_type, 8)
            + _pad(v.length, 6)
            + _pad(v.source, 14)
            + _pad(v.default, 12)
            + _pad(v.validation, 18)
            + v.description
        )
        lines.append(row)

    lines.append("─" * 104)
    lines.append(f"TOTAL VARIABLES: {len(vars_to_render)}")
    lines.append("")

    return "\n".join(lines)


def _default_vars():
    """Fallback variables when none are extracted."""
    from parser.tpf_parser import Variable

    return [
        Variable(
            name="ENTRY_ID", directive="DS", operand="CL8",
            var_type="CHAR", length="08", source="SYSTEM",
            default="SPACES", validation="NOT NULL", description="Entry Identifier",
        ),
        Variable(
            name="ERR_CODE", directive="DS", operand="CL4",
            var_type="CHAR", length="04", source="SYSTEM",
            default="0000", validation="NUMERIC", description="Error Code",
        ),
        Variable(
            name="RET_CODE", directive="DS", operand="F",
            var_type="BIN", length="04", source="SYSTEM",
            default="0", validation="NUMERIC", description="Return Code",
        ),
    ]
